src/AbbyWebsite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from artwork.views import main

urlpatterns = [
    url(r'^$',main),
    url(r'^admin/', admin.site.urls),
    url(r'^artwork/',include('artwork.urls',namespace='artwork')),
    url(r'^comments/',include('comments.urls',namespace='comments'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/artwork/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^upload/$',views.upload_file,name='upload'),
    url(r'^art_info/$',views.art_info,name='art_info'),
    url(r'^(?P<artcontext>[a-z_]+)/(?P<art_id>[a-z0-9]+)$',views.art_view,name='art_view'),
    url(r'^(?P<artcontext>[a-z_]+)/$',views.art_view,name='art_view'),
    #------------------------ url(r'^personal/$',views.personal,name='personal')
]

src/comments/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^like/$',views.like,name='like'),
    url(r'^get_comments/$',views.get_comments,name='get_comments'),
    #------------------------ url(r'^personal/$',views.personal,name='personal')
]

src/artwork/models.py
from django.db import models
from sorl.thumbnail import ImageField
from PIL import Image
from io import BytesIO

class ArtworkContext(models.Model):
    created_for = models.SlugField(unique=True,primary_key=True)
    description=models.CharField(max_length=100)
    
    def __str__(self):
        return self.description

class Artwork(models.Model):
    created_for=models.ForeignKey(ArtworkContext)
    name=models.CharField(max_length=100)
    description=models.CharField(max_length=200)
    created_on = models.DateField(blank=True,null=True)
    medium = models.CharField(max_length=100,blank=True,null=True)
    width = models.IntegerField(blank=True,null=True)
    height = models.IntegerField(blank=True,null=True)
    image = ImageField(upload_to='artwork/',blank=True,null=True)
    
    def get_image(self):
        if self.image is not None:
            return self.image.url
        else:
            return '#'
        
    def __str__(self):
        return self.name
        

src/comments/models.py
from django.db import models
from artwork.models import Artwork

# Create your models here.
class Comment(models.Model):
    artwork = models.ForeignKey(Artwork)
    posted_by = models.CharField(max_length=60,blank=False)
    posted_at = models.DateTimeField(auto_now_add=True)
    comment = models.CharField(max_length=200)
    
    def __str__(self):
        return self.comment
    
    #Returns a "pretty" string of the date/time posted
    def time_posted(self):
        DATE_FORMAT = "%Y-%m-%d"
        TIME_FORMAT = "%I:%M"
        retval = self.posted_at.strftime("%s %s" % (DATE_FORMAT, TIME_FORMAT))
        return retval
    
class Like(models.Model):
    artwork = models.ForeignKey(Artwork)
    number = models.IntegerField(default=0)
    
    def get_likes(self):
        return self.number
    
    def add_like(self):
        self.number = self.number + 1
        return self.number
    
    def remove_like(self):
        if self.number > 0:
            self.number = self.number - 1
        return self.number

src/artwork/forms.py
from django import forms

from artwork.models import Artwork

class ArtworkImageForm(forms.ModelForm):
    class Meta:
        model=Artwork
        fields=('created_for','name','description','created_on','image',)

src/comments/forms.py
from django import forms

from comments.models import Comment

class CommentForm(forms.ModelForm):
    artwork = forms.IntegerField(widget=forms.HiddenInput())
    
    class Meta:
        model=Comment
        fields=('posted_by','comment',)

src/artwork/views.py
from django.shortcuts import render,get_object_or_404
from .models import Artwork, ArtworkContext
from comments.forms import CommentForm
from pip._vendor import requests
from .forms import ArtworkImageForm
from .utils import handle_uploaded_image
from django.http.response import JsonResponse
import random

# Create your views here.
def art_view(request,artcontext):
    artwork_context = ArtworkContext.objects.get(created_for=artcontext)
    all_art = Artwork.objects.filter(created_for=artwork_context)
    comment_forms = {}
    if request.POST:
        for art in all_art:
            art_id = int(request.POST['artwork'])
            if art.id==art_id:
                comment_form = CommentForm(request.POST,initial={'artwork':art.id})
                if comment_form.is_valid():
                    comment = comment_form.save(commit=False)
                    comment.artwork = art
                    comment.save()
                else:
                    print(comment_form.errors)
            else:
                comment_form = CommentForm(initial={'artwork':art.id})
            comment_forms[art.id] = comment_form 
    else:
        for art in all_art:
            comment_forms[art.id] = CommentForm(initial={'artwork':art.id})
        
    return render(request,'artwork/'+artcontext+'.html',{'artwork':all_art,'comment_forms':comment_forms})

def main(request):
    max_id = Artwork.objects.order_by('-id')[0].id
    random_id = random.randint(1,max_id)
    art = Artwork.objects.filter(id__gte=random_id)[0]
    return render(request,'main.html',{'art':art})

def upload_file(request):
    if request.method == 'POST':
        form = ArtworkImageForm(request.POST,request.FILES)
        if form.is_valid():
            artwork = form.save(commit=False)
            t = handle_uploaded_image(request.FILES['image'])
            #filename,image
            artwork.image.save(t[0],t[1])
            artwork.save()
    else:
        form = ArtworkImageForm()
    return render(request, 'artwork/upload.html', {'form': form})

def art_info(request):
    return_fields = ['name','created_on','medium','width','height']
    if request.method == 'GET':
        art_id = request.GET['artwork_id']
        work_of_art = get_object_or_404(Artwork,id=art_id)
        ret_dict = {i:getattr(work_of_art,i) for i in return_fields}
    else:
        ret_dict = {}
    return JsonResponse(ret_dict)
        
        

#------------------------------------------------- def market_district(request):
    #--------- artwork_context = ArtworkContext.objects.get(created_for='ge_md')
    #------------- all_art = Artwork.objects.filter(created_for=artwork_context)
    #-- return render(request,'artwork/marketdistrict.html',{'artwork':all_art})
#------------------------------------------------------------------------------ 
#-------------------------------------------------------- def personal(request):
    #------ artwork_context = ArtworkContext.objects.get(created_for='personal')

src/comments/views.py
from django.http import JsonResponse
from artwork.models import Artwork
from comments.models import Like,Comment
from django.shortcuts import get_object_or_404

# Create your views here.
def like(request):
    if request.POST:
        artwork_id = request.POST['artwork_id']
        cur_artwork = Artwork.objects.get(id=artwork_id)
        #get_or_create returns a tuple, I don't care if it was created or not
        #so, only look at the 0th element of the tuple
        cur_like = Like.objects.get_or_create(artwork=cur_artwork)[0]
        number_of_likes = cur_like.add_like()
        cur_like.save()
    else:
        number_of_likes = 0
    out_dict = {'likes':number_of_likes}
    return JsonResponse(out_dict)

def get_comments(request):
    out_dict = {'comments':[]}
    if request.GET:
        art_id = request.GET['artwork_id']
        artwork = get_object_or_404(Artwork,id=art_id)
        all_comments = Comment.objects.filter(artwork=artwork).order_by('-posted_at')
        for comment in all_comments:
            cur_comment_list = [comment.time_posted(),comment.posted_by,comment.comment]
            out_dict['comments'].append(cur_comment_list)
    return JsonResponse(out_dict)

src/AbbyWebsite/templates/artwork/artwork_images.html
{% extends 'base.html' %}

{% load comment_extras %}
{% load thumbnail %}

{% block content %}
{% for art in artwork %}
<div class="img-container">
    {% thumbnail art.image "200x200" crop="center" as im %}
        <img class='thmbnl' src="{{ im.url }}"/>
    {% empty %}
        <p>No image</p>
    {% endthumbnail %}
    <div class="row">
        <div class="col-xs-6 col-s-6 col-md-6">
            <button id="{{art.id}}" class="btn btn-default like-button">
            {% csrf_token %}
            <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> Like
            </button>
        </div>
        <div class="col-xs-6 col-s-6 col-md-6">
        <button id="comment{{art.id}}" class="btn btn-default comment-button">
        <span class="glyphicon glyphicon-comment" aria-hidden="true"></span> Comment
        </button>
        </div>
    </div>
    <div class="modal fade" id="commentModal{{art.id}}" tabindex="-1" role="dialog" aria-labelledby="commentTitle">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="commentTitle">Comment</h4>
                </div>
                <div class="modal-body">
                    <img class="modal-image" id = "modal-image{{art.id}}" src="{{ art.image.url }}"/>
                    <div class="panel panel-default comments-panel">
                        <div class="panel-body comments">
                        </div>
                    </div>
                    <form id="comment_form{{art.id}}" method="post" action="" enctype = "multipart/form-data">
                        {% csrf_token %}
                        <p class='comment-form'>
                        {% for field in comment_forms|get_item:art.id %}
                            {% if not field.is_hidden %}
                                {{ field.errors }}{{ field.label_tag }} {{ field }}
                            {% else %}
                                {{ field.as_hidden }}
                            {% endif %}
                        {% endfor %}
                        </p>
                        <input type="submit" name="submit" value="Submit New Comment" />
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

src/AbbyWebsite/templates/artwork/ge_md.html
<!DOCTYPE HTML>
{% extends 'artwork/artwork_images.html' %}

{% block title %} Giant Eagle Market District {% endblock %}

{% block header %} Giant Eagle Market District {% endblock %}

src/AbbyWebsite/templates/artwork/personal.html
<!DOCTYPE HTML>
{% extends 'artwork/artwork_images.html' %}

{% block title %} Personal Projects {% endblock %}
{% block header %} Personal Projects {% endblock %}

<!--Images are handled in artwork_images.html, since all "image-type" sites will use the same overall design -->

src/AbbyWebsite/templates/artwork/upload.html
{% extends 'base.html' %}

{% block title %} Image Upload {% endblock %}

{% block header %} Image Upload {% endblock %}

{% block content %}
<form class="form-inline pull-left" method="post" action="{% url 'artwork:upload' %}" enctype="multipart/form-data">
{% csrf_token %}
{{form.as_p}}
<input type="submit" name="submit" value="Upload" />
</form>
{% endblock %}

src/AbbyWebsite/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html>
    <head>
        
        <!--Base CSS that I wrote for the site-->
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
        <!--Custom Google font family-->
        <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
        <!--JQuery-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script type="text/javascript" src = "{% static 'jquery/base.js' %}"></script>
        
        <!--Bootstrap-->
        <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        
        
        <title>{%block title%}{%endblock%}</title>
    </head>
    <body>
        <div id="sidebar">
            <h3>Gallery</h3>
            <nav>
            <ul class="nav nav-pills nav-stacked">
                <li role="presentation"><a href="{% url 'artwork:art_view' artcontext='ge_md' %}">Giant Eagle Market District</a></li>
                <li role="presentation"><a href="{% url 'artwork:art_view' artcontext='personal' %}">Personal Projects</a></li>
            </ul>
            </nav>
        </div>
        <div id="header-wrapper">
            <h1>
            {% block header %}
            {% endblock %}
            </h1>
        </div>
        <div id="content-wrapper" class="container">
            
            {% block content %}
            {% endblock %}
        </div>
        <div id="bigimage-wrapper" class="container">
        </div>
    </body>
</html>

src/AbbyWebsite/templates/main.html
{% extends 'base.html' %}

{% block content %}
<img src="{{ art.image.url }}"/>
{% endblock %}